version: '3.8'

services:
  service1:
    build: ./service1
    ports:
      - "8199:8199"
    depends_on:
      - service2
    networks:
      - internal_network

  service2:
    build: ./service2
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge 
